// src/Homepage/Layout/products.js
const products = [
    {
      id: 1,
      title: "Premium Wireless Headphones with ANC",
      currentPrice: 179.99,
      oldPrice: 229.99,
      category: "Electronics",
      image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1364&q=80",
      rating: 4.8,
      reviews: 255,
      badge: "hot",
      discount: "22% Off",
      color: ["black", "silver", "blue"],
      sizes: ["One Size"],
      brand: "Sony",
      subcategory: "headphones",
      description: "Immerse yourself in pure sound with these premium wireless headphones. Featuring industry-leading Active Noise Cancellation (ANC), crystal-clear audio, and a comfortable ergonomic design. Enjoy up to 35 hours of playtime with ANC off.",
      features: ["Active Noise Cancellation", "Hi-Res Audio Support", "Bluetooth 5.0", "Comfortable Earcups"],
      reviewsData: [
        { author: "Alice K.", rating: 5, date: "2025-05-12", comment: "Absolutely fantastic headphones! The ANC is incredible, and the sound quality is top-notch." },
        { author: "Ben M.", rating: 4, date: "2025-05-08", comment: "Very good overall. Comfortable for long use, but the touch controls take some getting used to." },
        { author: "Cindy L.", rating: 5, date: "2025-05-01", comment: "Best headphones I've ever owned. The battery life is also impressive." },
      ],
    },
    {
      id: 2,
      title: "Smart Watch with GPS and Heart Rate Monitor",
      currentPrice: 199.99,
      oldPrice: 259.99,
      category: "Wearables",
      image:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1399&q=80",
      rating: 4.5,
      reviews: 180,
      badge: "sale",
      discount: "23% Off",
      color: ["space gray", "rose gold", "midnight blue"],
      sizes: ["One Size"],
      brand: "FitTrack",
      subcategory: "smart-watches",
      description: "Track your fitness journey and stay connected with this advanced smartwatch. Features built-in GPS, continuous heart rate monitoring, sleep tracking, and smartphone notifications. Water-resistant up to 50 meters. Battery lasts up to 7 days.",
      features: ["GPS Tracking", "Heart Rate Monitoring", "Sleep Analysis", "Notification Alerts"],
      reviewsData: [
        { author: "David S.", rating: 4, date: "2025-05-10", comment: "A solid smartwatch for fitness tracking. The GPS is accurate, and the battery life is decent." },
        { author: "Emily R.", rating: 5, date: "2025-05-05", comment: "Love all the features! It's easy to use and looks great on my wrist." },
      ],
    },
    {
      id: 3,
      title: "Lightweight Performance Running Shoes",
      currentPrice: 119.99,
      category: "Footwear",
      image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=60",
      rating: 4.9,
      reviews: 310,
      badge: "new",
      color: ["neon green", "carbon black", "sky blue"],
      sizes: ["US 7", "US 8", "US 9", "US 10", "US 11"],
      brand: "ApexRun",
      subcategory: "running-shoes",
      description: "Experience ultimate comfort and speed with these lightweight performance running shoes. Designed with breathable mesh and responsive cushioning for optimal performance. Durable outsole provides excellent traction.",
      features: ["Breathable Mesh Upper", "Responsive Cushioning", "Durable Rubber Outsole", "Lightweight Design"],
      reviewsData: [
        { author: "Frank T.", rating: 5, date: "2025-05-12", comment: "These shoes are incredibly light and comfortable. Perfect for my daily runs." },
        { author: "Grace W.", rating: 5, date: "2025-05-07", comment: "Excellent running shoes! Great support and they look fantastic." },
      ],
    },
    {
      id: 4,
      title: "Durable Water-Resistant Travel Backpack (40L)",
      currentPrice: 89.99,
      category: "Accessories",
      image: "https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=1528&q=80",
      rating: 4.6,
      reviews: 95,
      color: ["charcoal gray", "forest green", "deep blue"],
      sizes: ["One Size"],
      brand: "VoyagerGear",
      subcategory: "backpacks",
      description: "The ideal travel companion, this 40L backpack is made from durable, water-resistant material. Features multiple compartments for organized packing, comfortable padded straps, and a breathable back panel. Perfect for weekend getaways and longer trips.",
      features: ["Water-Resistant Material", "Multiple Compartments", "Padded Shoulder Straps", "Breathable Back Panel"],
      reviewsData: [
        { author: "Henry U.", rating: 4, date: "2025-05-09", comment: "Good quality backpack with plenty of space. The water resistance is a nice feature." },
        { author: "Ivy P.", rating: 5, date: "2025-05-03", comment: "Used this for a weekend trip and it was perfect. Very comfortable to carry." },
      ],
    },
    {
      id: 5,
      title: "Portable Bluetooth Speaker with Bass Boost",
      currentPrice: 59.99,
      oldPrice: 79.99,
      category: "Electronics",
      image: "https://images.unsplash.com/photo-1544168190-79c17527004f?auto=format&fit=crop&w=800&q=60",
      rating: 4.3,
      reviews: 112,
      badge: "sale",
      discount: "25% Off",
      color: ["black", "teal", "red"],
      sizes: ["One Size"],
      brand: "SoundWave",
      subcategory: "speakers",
      description: "Enjoy powerful sound on the go with this portable Bluetooth speaker. Features bass boost technology for rich low-end frequencies and a long-lasting battery. Water-resistant design makes it perfect for outdoor adventures.",
      features: ["Bass Boost Technology", "Bluetooth 5.0", "Water-Resistant (IPX5)", "Up to 12 Hours Playtime"],
      reviewsData: [
        { author: "Jack Q.", rating: 4, date: "2025-05-11", comment: "Great sound for its size. The bass boost really makes a difference." },
        { author: "Kelly R.", rating: 5, date: "2025-05-06", comment: "Perfect for taking to the beach. The battery lasts all day." },
      ],
    },
    {
      id: 6,
      title: "Ergonomic Wireless Gaming Mouse with RGB",
      currentPrice: 69.99,
      oldPrice: 99.99,
      category: "Accessories",
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1470&q=80",
      rating: 4.7,
      reviews: 288,
      badge: "hot",
      discount: "30% Off",
      color: ["black", "white"],
      sizes: ["One Size"],
      brand: "GameMaster",
      subcategory: "mice",
      description: "Dominate your games with this ergonomic wireless gaming mouse. Features customizable RGB lighting, programmable buttons, and high-precision tracking for ultimate control and comfort during long gaming sessions.",
      features: ["Ergonomic Design", "Customizable RGB Lighting", "Programmable Buttons", "High-Precision Sensor"],
      reviewsData: [
        { author: "Liam Z.", rating: 5, date: "2025-05-12", comment: "This mouse is a game-changer! So comfortable and the customization options are great." },
        { author: "Mia Y.", rating: 4, date: "2025-05-07", comment: "Excellent mouse for gaming. The wireless connection is stable." },
      ],
    },
    {
      id: 7,
      title: "Slim Protective Laptop Sleeve (13-inch)",
      currentPrice: 34.99,
      oldPrice: 44.99,
      category: "Accessories",
      image: "https://www.tomtoc.com/cdn/shop/files/BL3A3003_1600x.jpg?v=1733801696",
      rating: 4.4,
      reviews: 135,
      badge: "new",
      discount: "21% Off",
      color: ["space gray", "navy blue", "mint green"],
      sizes: ["13-inch"],
      brand: "TechGuard",
      subcategory: "laptop-sleeves",
      description: "Protect your 13-inch laptop with this slim and stylish protective sleeve. Made from durable, water-resistant material with a soft interior lining to prevent scratches. Lightweight and easy to carry.",
      features: ["Durable Outer Material", "Soft Interior Lining", "Slim and Lightweight", "Water-Resistant"],
      reviewsData: [
        { author: "Noah B.", rating: 4, date: "2025-05-10", comment: "Does exactly what it's supposed to. My laptop feels secure." },
        { author: "Olivia C.", rating: 5, date: "2025-05-04", comment: "Love the color and how slim it is. Fits perfectly in my bag." },
      ],
    },
    {
      id: 8,
      title: "Fast Wireless Charging Pad (Qi Certified)",
      currentPrice: 39.99,
      oldPrice: 49.99,
      category: "Electronics",
      image: "https://images.unsplash.com/photo-1584735935682-5b619b9585cc?auto=format&fit=crop&w=800&q=60",
      rating: 4.2,
      reviews: 168,
      badge: "sale",
      discount: "20% Off",
      color: ["black", "white"],
      sizes: ["One Size"],
      brand: "PowerUp",
      subcategory: "chargers",
      description: "Charge your Qi-enabled devices quickly and efficiently with this fast wireless charging pad. Features a sleek, non-slip design and overcharge protection for safety. Compatible with most wireless charging smartphones.",
      features: ["Fast Wireless Charging", "Qi Certified", "Non-Slip Design", "Overcharge Protection"],
      reviewsData: [
        { author: "Peter D.", rating: 4, date: "2025-05-09", comment: "Works well and charges my phone quickly. Looks good on my desk." },
        { author: "Quinn E.", rating: 3, date: "2025-05-02", comment: "Sometimes it's a bit finicky with placement, but overall it does the job." },
      ],
    },
    {
      id: 9,
      title: "Non-Slip Yoga Mat with Alignment Lines (5mm)",
      currentPrice: 29.99,
      category: "Fitness",
      image: "https://images.unsplash.com/photo-1532658917184-196464133dc3?auto=format&fit=crop&w=800&q=60",
      rating: 4.7,
      reviews: 220,
      badge: "new",
      color: ["purple", "gray", "ocean blue"],
      sizes: ["One Size"],
      brand: "ZenFlow",
      subcategory: "yoga-mats",
      description: "Enhance your yoga and fitness routines with this high-quality, non-slip yoga mat. Features alignment lines to help with posture and a comfortable 5mm thickness for cushioning. Eco-friendly and easy to clean.",
      features: ["Non-Slip Surface", "Alignment Lines", "5mm Thickness", "Eco-Friendly Material"],
      reviewsData: [
        { author: "Rachel F.", rating: 5, date: "2025-05-11", comment: "This mat is fantastic! The grip is excellent and the alignment lines are very helpful." },
        { author: "Sam G.", rating: 4, date: "2025-05-06", comment: "Good quality mat. Comfortable and doesn't slip." },
      ],
    },
    {
      id: 10,
      title: "Adjustable Aluminum Smartphone Stand",
      currentPrice: 24.99,
      oldPrice: 29.99,
      category: "Electronics",
      image: "https://images.unsplash.com/photo-1591817994764-015b8411a233?auto=format&fit=crop&w=800&q=60",
      rating: 4.5,
      reviews: 105,
      badge: "hot",
      discount: "17% Off",
      color: ["black", "silver"],
      sizes: ["One Size"],
      brand: "SmartHold",
      subcategory: "smartphone-accessories",
      description: "Keep your smartphone at the perfect viewing angle with this sturdy and adjustable aluminum stand. Features a foldable design for portability and anti-slip pads to keep your device secure. Ideal for watching videos, video calls, and more.",
      features: ["Adjustable Angle", "Foldable Design", "Anti-Slip Pads", "Durable Aluminum"],
      reviewsData: [
        { author: "Tina H.", rating: 4, date: "2025-05-09", comment: "Very useful stand. Sturdy and easy to adjust." },
        { author: "Victor I.", rating: 5, date: "2025-05-03", comment: "Exactly what I needed for my desk. Great quality." },
      ],
    },
    // Added for Electronics
    { id: 11, title: "27-inch 4K UHD IPS Monitor", currentPrice: 399.99, category: "Electronics", subcategory: "laptops", image: "https://images.unsplash.com/photo-1517336714731-489689fd1728?auto=format&fit=crop&w=800&q=60", brand: "DisplayPro", description: "Experience stunning visuals with this 27-inch 4K UHD IPS monitor. Features vibrant colors, wide viewing angles, and a sleek bezel-less design. Perfect for work and entertainment.", features: ["4K UHD Resolution", "IPS Panel", "Bezel-less Design", "Multiple Ports"] },
    { id: 12, title: "RGB Mechanical Gaming Keyboard with Cherry MX Switches", currentPrice: 149.99, category: "Electronics", subcategory: "accessories", image: "https://images.unsplash.com/photo-1555753141-91a7e8d7951a?auto=format&fit=crop&w=800&q=60", brand: "KeyMaster", description: "Enjoy a premium tactile typing experience with this RGB mechanical gaming keyboard. Features Cherry MX Brown switches, customizable RGB backlighting, and anti-ghosting technology for precise input.", features: ["Cherry MX Brown Switches", "Customizable RGB", "Anti-Ghosting", "Durable Build"] },
  
    // Added for Fashion
    {id: 13, title: "Genuine Leather Classic Belt", currentPrice: 59.99, category: "Fashion", subcategory: "accessories", image: "https://images.unsplash.com/photo-1571946864311-788a57494877?auto=format&amp;fit=crop&amp;w=800&amp;q=60", brand: "BeltCraft", description: "A timeless classic, this genuine leather belt is the perfect accessory for any outfit. Features a durable metal buckle and a smooth, rich leather finish. Available in various waist sizes.", features: ["Genuine Leather", "Durable Metal Buckle", "Classic Design", "Various Sizes"] },
    { id: 14, title: "Wide Brim Summer Beach Hat with UV Protection", currentPrice: 34.99, category: "Fashion", subcategory: "accessories", image: "https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&amp;fit=crop&amp;w=800&amp;q=60", brand: "SunShine", description: "Stay protected from the sun in style with this wide brim summer beach hat. Made from lightweight, breathable material with built-in UV protection. Perfect for beach days and outdoor activities.", features: ["Wide Brim for Sun Protection", "Lightweight and Breathable", "UV Protection", "Stylish Design"] },
    
    // Added for Home & Living
    { id: 15, title: "Luxury 100% Cotton Bedding Set (Queen)", currentPrice: 129.99, category: "Home & Living", subcategory: "furniture", image: "https://images.unsplash.com/photo-1567016546078-1d6740a26779?auto=format&amp;fit=crop&amp;w=800&amp;q=60", brand: "SleepWell", description: "Indulge in comfort with this luxurious 100% cotton bedding set. Includes a duvet cover, two pillowcases, and a fitted sheet. Soft, breathable, and perfect for a restful night's sleep. Available in Queen size.", features: ["100% Cotton", "Soft and Breathable", "Queen Size", "Includes Duvet Cover, Pillowcases, Fitted Sheet"] },
    { id: 16, title: "Elegant Ceramic Dinnerware Set for Four", currentPrice: 99.99, category: "Home & Living", subcategory: "kitchenware", image: "https://images.unsplash.com/photo-1556912495-b64949b289e3?auto=format&amp;fit=crop&amp;w=800&amp;q=60", brand: "TableJoy", description: "Elevate your dining experience with this elegant ceramic dinnerware set. Includes dinner plates, salad plates, bowls, and mugs for four people. Durable and stylish for everyday use or special occasions.", features: ["Ceramic Material", "Set for Four", "Durable and Stylish", "Microwave and Dishwasher Safe"] },
    { id: 17, title: "Aromatherapy Scented Candles (Set of 3)", currentPrice: 29.99, category: "Home & Living", subcategory: "decor", image: "https://images.unsplash.com/photo-1598515889769-9081c1f1894c?auto=format&amp;fit=crop&amp;w=800&amp;q=60", brand: "AromaHome", description: "Create a relaxing and inviting atmosphere with this set of three aromatherapy scented candles. Each candle is made with natural essential oils for a long-lasting and soothing fragrance. Perfect for unwinding after a long day.", features: ["Set of 3 Candles", "Natural Essential Oils", "Long-Lasting Scent", "Various Soothing Fragrances"] },
    { id: 18, title: "Modern LED Desk Lamp with Adjustable Brightness", currentPrice: 49.99, category: "Home & Living", subcategory: "lighting", image: "https://images.unsplash.com/photo-1512941777337-4181160d1174?auto=format&amp;fit=crop&amp;w=800&amp;q=60", brand: "LightUp", description: "Illuminate your workspace with this modern LED desk lamp. Features adjustable brightness levels and a flexible gooseneck for optimal lighting. Energy-efficient LED bulb provides bright and comfortable light for reading and working.", features: ["Adjustable Brightness", "Flexible Gooseneck", "Energy-Efficient LED", "Modern Design"] },
    ];
    
    export default products;
    
    